### ISSUE TITLE
py-des communications

### ISSUE THREAD

**Issue by CygnusKernow** [vitostamatti/pydes#5]
From: https://pydes.readthedocs.io/en/latest/#feedback-and-support

"Feedback and Support
If you have any questions, suggestions, or feedback regarding py-des, feel free to reach out via GitHub issues or the official communication channels."

What are the official communication channels?

Regards,

Stuart

**Comment by vitostamatti** [comment]
hey! there're no "official" channels other than this one. This is just a side project i created to explore a bit on this field. If you have any interest into adding more stuff, you are more than welcome 👍
