### ISSUE TITLE
Question on performance

### ISSUE THREAD

**Issue by salabim** [vitostamatti/pydes#6]
I was looking at your code for wait_for and request and it looks like you are checking the condition on every event tick.
If that's right, it can be very inefficient when many events do not change the state at all.

The salabim package does implement that completely differently, thus potentially resulting in faster execution.

Ruud van der Ham
core developer salabim

**Comment by vitostamatti** [comment]
i'd take a look to take your implementation approach. I'm sure mine could be improved. Thank you for the suggestion! 👍

**Comment by salabim** [comment]
I see that you have closed this issue.
Does that mean that you have indeed changed the inefficient implementation?

**Comment by vitostamatti** [comment]
Your  suggestion is appretiated and hopefully someday i'll have the time to look into it. Or maybe you could help me improve it if you already did it in salabim. That would be very helpful 😄  Thanks!

**Comment by salabim** [comment]
What advantage has PyDes over salabim, anyway, if any?
